CREATE DATABASE IF NOT EXISTS Exercise_04;
USE Exercise_04;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    User_ID INT PRIMARY KEY AUTO_INCREMENT,
    FullName VARCHAR(100),
    Phone INT
);

INSERT INTO USERS (FullName, Phone) VALUES
('Nguyễn Văn A', 981234567),
('Trần Thị B', 912345678),
('Lê Văn C', 123456789);

ALTER TABLE USERS
MODIFY Phone VARCHAR(15);

SELECT * FROM USERS;